const products=[
 {brand:'BAYRAKTAR',title:'TB2',number:'01',stat:'27,030 feet',image:'mNkuVlM07JWOBgaGIHmOO2aR5zOhGV0S.png',href:'bayraktar-tb2/'},
 {brand:'',title:'AKINCI',number:'02',stat:'45,118 feet',image:'8Bu70ey5Ux6irMkQ87vLXm0XLAmVuyJS.png',href:'bayraktar-akinci/'},
 {brand:'BAYRAKTAR',title:'KIZILELMA',number:'03',stat:'45.000 feet',image:'f33Rybz83VEh5uozBsctuDGRIY2XI8ps.png',href:'bayraktar-kizilelma/'},
 {brand:'BAYRAKTAR',title:'TB3',number:'04',stat:'25.000 feet',image:'PJPeeYzYm5vFfrL3cGN1XRn6hEigAoUU.png',href:'bayraktar-tb3/'},
 {brand:'BAYRAKTAR',title:'KALKAN DİHA',number:'05',stat:'10.000 feet',image:'bbqEbjPnYHF2mrD4fau56uqnFdBdSAlU.png',href:'bayraktar-diha/'},
 {brand:'',title:'KEMANKEŞ 1',number:'06',stat:'150 km menzil',image:'ycVwnZyGKFw1gGoHGukyyeRCkk0Xjpbq.png',href:'kemankes/'},
 {brand:'',title:'KEMANKEŞ 2',number:'07',stat:'10.000 feet',image:'CrdJi821iemyVmCCOul6KYc5wiknHsHs.png',href:'kemankes2/'},
 {brand:'BAYRAKTAR',title:'MİNİ İHA',number:'08',stat:'15+ km menzil',image:'iZv0BqC7owVr1ow6Sec4VbcgWhFtXEXW.png',href:'bayraktar-mini-iha/'}
];
const cdn='https://cdn.baykartech.com/media/upload/userFormUpload/';let active=1;const art=document.querySelector('.hero-art'),name=document.querySelector('#hero-title'),brand=document.querySelector('#hero-brand'),num=document.querySelector('#hero-number'),stat=document.querySelector('#hero-stat'),link=document.querySelector('#hero-link'),dots=document.querySelector('.hero-dots');
products.forEach((p,i)=>{const b=document.createElement('button');b.setAttribute('role','tab');b.setAttribute('aria-label',`${p.number} ${p.title}`);b.addEventListener('click',()=>show(i));dots.append(b)});
function show(i){active=(i+products.length)%products.length;const p=products[active];art.style.backgroundImage=`linear-gradient(90deg,#142448b5 0%,transparent 60%),url('${cdn+p.image}')`;name.textContent=p.title;brand.textContent=p.brand;brand.hidden=!p.brand;num.textContent=p.number;stat.textContent=p.stat;link.href=`https://baykartech.com/tr/uav/${p.href}`;dots.querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',j===active);b.setAttribute('aria-selected',j===active)});document.querySelector('.flight-data b').textContent=`${String(active+1).padStart(2,'0')} / 08`}
show(active);document.querySelector('.hero-arrow.prev').addEventListener('click',()=>show(active-1));document.querySelector('.hero-arrow.next').addEventListener('click',()=>show(active+1));window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(active-1);if(e.key==='ArrowRight')show(active+1)});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',open?'Menüyü kapat':'Menüyü aç')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const compare=document.querySelector('#comparison'),handle=document.querySelector('.compare-handle'),after=document.querySelector('.plane-after'),line=document.querySelector('.compare-line');let dragging=false;function setCompare(event){const box=compare.getBoundingClientRect(),x=Math.max(0,Math.min(1,(event.clientX-box.left)/box.width))*100;after.style.clipPath=`inset(0 0 0 ${x}%)`;line.style.left=`${x}%`;handle.style.left=`${x}%`;handle.setAttribute('aria-valuenow',Math.round(x));document.querySelector('.compare-tag').style.left=`calc(${x}% + 27px)`}handle.addEventListener('pointerdown',e=>{dragging=true;handle.setPointerCapture(e.pointerId);setCompare(e)});handle.addEventListener('pointermove',e=>{if(dragging)setCompare(e)});handle.addEventListener('pointerup',()=>dragging=false);compare.addEventListener('click',e=>setCompare(e));handle.addEventListener('keydown',e=>{if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;e.preventDefault();const current=Number(handle.getAttribute('aria-valuenow'));const next=Math.max(0,Math.min(100,current+(e.key==='ArrowRight'?5:-5)));const box=compare.getBoundingClientRect();setCompare({clientX:box.left+box.width*next/100})});

